### ISSUE TITLE
Celé jméno na video talku?

### ISSUE THREAD

**Issue by rpavelka** [martin-kokos/pyvo-pyannotate-demo#2]
Ahoj, Martine,

dělám video střih Tvého talku na Pyvu a obvykle tam dáváme jméno a přijmení, třeba [takto](https://www.youtube.com/watch?v=uJZdJCN7AJo), ale u Tebe jej nemožu dohledat na [pyvo.cz/brno-pyvo/2017-11](https://pyvo.cz/brno-pyvo/2017-11/). Jak bys tam chtěl být, prosím Tě?

Dík.

Roman

**Comment by martin-kokos** [comment]
Asi uz neni relevantni.
